Coloured events
tekdi/eg-website pull request #204
Opened 2023-06-22 15:48 UTC by nyb12

2023-06-23 08:36 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/front-end/orientation/Orientation.js
> +                  <AdminTypo.H6 bold>Prerak Orientation</AdminTypo.H6>
Get this from enum API and show accordingly.

2023-06-23 08:36 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/front-end/orientation/Orientation.js
> +                        : "#EAB431",
Use enum API color

2023-06-23 10:18 UTC, nyb12 commented on apps/front-end/src/pages/front-end/orientation/Orientation.js
> +                        : "#EAB431",
added in constants in common-lib

2023-06-26 10:57 UTC, sagarkoshti1990 requested changes

2023-06-26 10:57 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/front-end/orientation/Orientation.js
> +                      item?.type === "prerak_orientation"
change to `EVENTS_COLORS[item?.type]`

2023-06-26 10:57 UTC, sagarkoshti1990 commented on lib/common-lib/src/config/constant.js
> +  yellow: '#EAB431'
change to event type value from enum API.

2023-06-27 04:15 UTC, sagarkoshti1990 approved these changes

2023-06-27 04:51 UTC, merged