Added conditional alert message
tekdi/eg-website pull request #292
Opened 2023-07-07 13:05 UTC by Dhanashree-Patil95

-Conditional alert message added in Docschecklist.js file
-Changes in translation files

2023-07-07 13:59 UTC, sagarkoshti1990 approved these changes

2023-07-10 05:46 UTC, sagarkoshti1990 requested changes

2023-07-10 05:46 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/front-end/ag-form/Docschecklist.js
>            <></>
change to `<React.Fragment/>`

2023-07-10 05:54 UTC, Dhanashree-Patil95 commented on apps/front-end/src/pages/front-end/ag-form/Docschecklist.js
>            <></>
Resolved

2023-07-10 06:08 UTC, sagarkoshti1990 approved these changes

2023-07-10 06:47 UTC, merged