[Fix] Sentry errors in beneficiary journey and facilitatorQualification.
tekdi/eg-website pull request #302
Opened 2023-07-11 06:57 UTC by chaitanyakole

r.replaceAll is not a function
r.filter is not a function

2023-07-11 13:30 UTC, sagarkoshti1990 requested changes

2023-07-11 13:30 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/front-end/BenificiaryJourney.js
> +    const uniqueDates = Array.result.reduce(
this is wrong implementation. `Array`

2023-07-11 14:34 UTC, chaitanyakole commented on apps/front-end/src/pages/front-end/BenificiaryJourney.js
> +    const uniqueDates = Array.result.reduce(
can you suggest me what can I do for that??

2023-07-13 07:07 UTC, sagarkoshti1990 approved these changes

2023-07-28 04:04 UTC, closed without merging