Aadhar kyc
tekdi/eg-website pull request #39
Opened 2023-05-22 21:38 UTC by Amay515

Created All the screen for Aadhar Kyc

2023-05-23 05:55 UTC, manojLondhe requested changes

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarKyc.js
> +      "x-client-id": "401c3159-bbfe-438d-a62c-eb4ff8bb8c10",
use env file to get client id, secret and base URL

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarKyc.js
> +      const url2 = `https://dg-sandbox.setu.co/api/okyc/${id}/initiate/`;
use env file to get  base URL

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarKyc.js
> +    const url1 = "https://dg-sandbox.setu.co/api/okyc/";
use env file to get  base URL

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarKyc.js
> +    const url = `https://dg-sandbox.setu.co/api/okyc/${kycReqID}/verify`;
use env file to get  base URL

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarKyc.js
> +      "x-client-id": "401c3159-bbfe-438d-a62c-eb4ff8bb8c10",
use env file to get client id, secret and base URL

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/routes/admin.js
> +    path: '/adharStart',
correct spellings everywhere 
adhar => aadhaar

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarKyc.js
> +          Offline Aadhaar Verification
use lang file for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarKyc.js
> +          <label htmlFor="aadhaarNumber">Enter Your Aadhaar Number</label>
use lang file for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarKyc.js
> +            <span>Enter Security Code</span>
use lang file for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarKyc.js
> +          We will send you an OTP to the mobile number linked with your Aadhaar
use lang file for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarKyc.js
> +            I agree to download my Aadhaar XML file from the UIDAI Website to
use lang file for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarKyc.js
> +            I understand that my Aadhaar details shall not be used or stored for
use lang file for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarKyc.js
> +          I have read and understood all of the points above
use lang file for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarKyc.js
> +          <Text color="white">Continue</Text>
use lang file for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarOTP.js
> +        "Content-Type": "application/json",
use env file to get client id, secret and base URL

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/QrScannerKyc/QrScannerKyc.js
> +        <h2>Scan Your Aadhaar QR Code</h2>
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/QrScannerKyc/QrScannerKyc.js
> +          <Text color="white">Continue</Text>
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/ManualUpload/ManualUpload.js
> +            <h2>Aadhaar Card</h2>
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/ManualUpload/ManualUpload.js
> +            <Text>Upload a photo or scan of your card</Text>
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/ManualUpload/ManualUpload.js
> +                    <Text>Upload the front side of your Aadhaar card</Text>
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/ManualUpload/ManualUpload.js
> +                  <Text>Upload the back side of your Aadhaar card</Text>
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/ManualUpload/ManualUpload.js
> +                <Text color="white">Upload Again</Text>
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/ManualUpload/ManualUpload.js
> +              <Text color="white">Continue</Text>
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/ManualUpload/ManualUpload.js
> +              <span>Aadhaar Card Uploaded</span>
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/ManualUpload/ManualUpload.js
> +              <h4>Front View</h4>
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/ManualUpload/ManualUpload.js
> +              <h4>Back View</h4>
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadharStartKyc.js
> +          Skip to Login
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadharStartKyc.js
> +        <Text textAlign="center" mb="4">We have sent you a text message with username and password on your mobile number</Text>
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadharStartKyc.js
> +        <p>Your Application is Submitted Successfully!</p>
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadharStartKyc.js
> +          <Text fontSize="md" fontWeight="medium" color="gray.600">Aadhaar Number KYC</Text>
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadharStartKyc.js
> +          <span style={{ fontSize: "13px" }}>Mobile Number is not linked to Aadhaar Card</span>
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarSuccess.js
> +          Offline Aadhaar Verification
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarSuccess.js
> +          <span>Your Aadhaar Verification is successful</span>
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarSuccess.js
> +          <Text color="white">Continue Login</Text>
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarOTP.js
> +          <Text color="white">Continue</Text>
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarOTP.js
> +              Set a 4 digit passcode to securely share your Aadhaar zip filee
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarOTP.js
> +          <label htmlFor="otpNumber">Enter 6 digit OTP</label>
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 05:55 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarOTP.js
> +          Offline Aadhaar Verification
use lang file and strings for all UI text - add text for both hindi, english

2023-05-23 12:40 UTC, Amay515 commented on apps/front-end/src/pages/front-end/AadhaarKyc/AadhaarKyc.js
> +      "x-client-id": "401c3159-bbfe-438d-a62c-eb4ff8bb8c10",
done

2023-05-26 11:27 UTC, manojLondhe commented
closing in favour of https://github.com/tekdi/eg-website/pull/49

2023-05-26 11:27 UTC, closed without merging