Learner Duplication list and Assigning to certain prerak
tekdi/eg-website pull request #391
Opened 2023-08-03 12:04 UTC by swapnilphalke03

https://tracker.tekdi.net/issues/201622

https://tracker.tekdi.net/issues/201623

2023-08-08 11:08 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/admin/duplicate/DuplicateView.js
> +      name: t("LEARNERS") + " " + t("Name"),
this is not correct language constant, please add new

2023-08-08 11:11 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/admin/duplicate/DuplicateView.js
> +            {row?.last_name ? row?.last_name : ""}
if `last_name` is not exist so `first_name` and white space is showing. please add this before `last_name` in this condition

2023-08-08 11:11 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/admin/duplicate/DuplicateView.js
> +
remove white spaces.

2023-08-08 12:50 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/admin/duplicate/DuplicateTable.js
> +
Remove white spaces.

2023-08-08 12:51 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/admin/duplicate/DuplicateTable.js
> +      attr: "aadhaar ",
`attr: "aadhaar ",` this space is need ??

2023-08-08 12:52 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/admin/duplicate/DuplicateTable.js
> +      attr: "Count",
check this attr is capitalised ??

2023-08-08 12:55 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/admin/duplicate/DuplicateTable.js
> +          <Image
please use the `<IconByName />` instead of image

2023-08-08 12:56 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/admin/duplicate/DuplicateTable.js
> +            }}
`IconByName` is not accept the source prop please use correct props.

2023-08-09 11:24 UTC, sagarkoshti1990 requested changes

2023-08-09 11:24 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/admin/duplicate/DuplicateView.js
> +                      {`${t("LEARNERS")} ${t("NAME")}:`}
this is not correct language constant, please add new

2023-08-10 07:41 UTC, manojLondhe commented on lib/common-lib/src/services/facilitatorRegistryService.js
> +export const getDuplicateList = async (params = {}, header = {}) => {
move this to /lib/common-lib/src/services/benificiaryRegistoryService.js

2023-08-10 07:41 UTC, manojLondhe commented on lib/common-lib/src/services/facilitatorRegistryService.js
> +export const assignToPrerak = async (params = {}, header = {}) => {
move this to /lib/common-lib/src/services/benificiaryRegistoryService.js

2023-08-10 07:41 UTC, manojLondhe commented on lib/common-lib/src/services/facilitatorRegistryService.js
> +export const getDetailsByadhaar = async (params = {}, header = {}) => {
move this to /lib/common-lib/src/services/benificiaryRegistoryService.js

2023-08-10 08:03 UTC, manojLondhe requested changes

2023-08-10 08:03 UTC, manojLondhe commented on apps/front-end/src/routes/admin.js
change path and file names as

```
  { path: "/admin/learners", component: AdminBeneficiariesList },
  { path: "/admin/learners/duplicates", component: AdminBeneficiariesDuplicatesList },
  { path: "/admin/learners/duplicates/:aadhaarNo", component: AdminBeneficiariesDuplicatesByAadhaar },
```

2023-08-10 09:25 UTC, swapnilphalke03 commented on lib/common-lib/src/components/helper.js
> +export const tableCustomStyles = {
I checked writting in css file, but the data table we are using it need the styling in this formate itself.

2023-08-10 11:18 UTC, merged