Bug #202248 : District block change status remove values
tekdi/eg-website pull request #401
Opened 2023-08-07 09:31 UTC by swapnilphalke03

### I have ensured that following `Pull Request Checklist` is taken care of before sending this PR
* [ ] Code is formatted as per format decided
* [ ] Updated acceptance criteria in tracker
* [ ] Updated test cases in test-cases-tracker

https://tracker.tekdi.net/issues/202248

2023-08-07 14:53 UTC, sagarkoshti1990 requested changes

2023-08-07 14:53 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/front-end/ag-edit/address/addressEdit.js
> +        block: null,
I thing this is not working when you set the value to input select.

2023-08-08 06:07 UTC, swapnilphalke03 commented
/home/ttpl-rt-059/Downloads/screen-capture (3).mp4

2023-08-09 05:56 UTC, sagarkoshti1990 approved these changes

2023-08-09 05:59 UTC, sagarkoshti1990 approved these changes

2023-08-09 06:22 UTC, merged