Changes in prerak bio page ( removed this black braces {" "}  )
tekdi/eg-website pull request #424
Opened 2023-08-10 12:31 UTC by chaitanyakole

### I have ensured that following `Pull Request Checklist` is taken care of before sending this PR
* [x] Code is formatted as per format decided
* [x] Updated acceptance criteria in tracker
* [x] Updated test cases in test-cases-tracker

2023-08-10 12:58 UTC, sagarkoshti1990 requested changes

2023-08-10 12:58 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/admin/facilitator/View.js
> -                <HStack width={"100%"}>
why this remove ?

2023-08-10 13:34 UTC, sagarkoshti1990 commented
No bug and task no in PR title. please add.

2023-08-11 03:48 UTC, chaitanyakole commented on apps/front-end/src/pages/admin/facilitator/View.js
> -                <HStack width={"100%"}>
Yesterday as we discuss in meeting

2023-08-11 12:15 UTC, closed without merging