Bug #203354  Father and Mother middle and Last name accepting number
tekdi/eg-website pull request #437
Opened 2023-08-18 11:03 UTC by swapnilphalke03

### I have ensured that following `Pull Request Checklist` is taken care of before sending this PR
* [ ] Code is formatted as per format decided
* [ ] Updated acceptance criteria in tracker
* [ ] Updated test cases in test-cases-tracker
https://tracker.tekdi.net/issues/203354

2023-08-18 13:38 UTC, sagarkoshti1990 requested changes

2023-08-18 13:38 UTC, sagarkoshti1990 commented on lib/common-lib/src/components/helper.js
> +  defaultVlaueAll = ''
don't remove this

2023-08-21 06:47 UTC, swapnilphalke03 commented on lib/common-lib/src/components/helper.js
> +  defaultVlaueAll = ''
Resolved.

2023-08-21 06:54 UTC, sagarkoshti1990 approved these changes

2023-08-21 07:12 UTC, merged