#204396 : Camp dashboard and flow.
tekdi/eg-website pull request #511
Opened 2023-09-11 08:44 UTC by swapnilphalke03

### I have ensured that following `Pull Request Checklist` is taken care of before sending this PR
* [ ] Code is formatted as per format decided
* [ ] Updated acceptance criteria in tracker
* [ ] Updated test cases in test-cases-tracker
https://tracker.tekdi.net/issues/204396
https://tracker.tekdi.net/issues/204397
https://tracker.tekdi.net/issues/204394
https://tracker.tekdi.net/issues/204393

2023-09-22 17:54 UTC, sagarkoshti1990 requested changes

2023-09-22 17:54 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/front-end/BenificiaryEnrollment.js
> +            "applied_but_pending",
Remove

2023-09-28 07:20 UTC, manojLondhe requested changes

2023-09-28 07:20 UTC, manojLondhe commented on apps/front-end/src/component/BaseInput.js
> +const CheckUncheck = ({ required, schema, value, onChange }) => {
add comment for what is this for?

2023-09-28 07:20 UTC, manojLondhe commented on apps/front-end/src/component/formCustomeInputs/FileUpload.js
> +      user_id: userId || localStorage.getItem("id"),
what does localStorage.getItem("id") contain?

2023-09-28 07:20 UTC, manojLondhe commented on lib/common-lib/src/services/campRegistoryService.js
> +import { post, patch, handleResponseException } from './RestClient'
just rename as campService.js

2023-09-28 07:44 UTC, swapnilphalke03 commented on apps/front-end/src/pages/front-end/Camp/CampDashboard.js
> +            title="YouTube video player"
Resolved.

2023-09-28 07:45 UTC, swapnilphalke03 commented on apps/front-end/src/routes/routes.js
> +    path: "/camps/LearnerList",
Change done.

2023-09-28 07:45 UTC, swapnilphalke03 commented on lib/common-lib/src/services/campRegistoryService.js
> +export const createConsent = async (params = {}, header = {}) => {
Resolved

2023-09-28 07:47 UTC, swapnilphalke03 commented on lib/common-lib/src/services/campRegistoryService.js
> +import { post, patch, handleResponseException } from './RestClient'
Renamed.

2023-09-28 07:47 UTC, swapnilphalke03 commented on apps/front-end/src/component/BaseInput.js
> +const CheckUncheck = ({ required, schema, value, onChange }) => {
comment added

2023-09-28 07:48 UTC, swapnilphalke03 commented on apps/front-end/src/component/formCustomeInputs/FileUpload.js
> +      user_id: userId || localStorage.getItem("id"),
id of the logged-in user, comment added

2023-09-28 09:17 UTC, merged