Create assessment module in EG
tekdi/eg-website pull request #725
Opened 2023-11-29 11:14 UTC by Aar-if

### I have ensured that following `Pull Request Checklist` is taken care of before sending this PR
* [ ] Code is formatted as per format decided
* [ ] Updated acceptance criteria in tracker
* [ ] Updated test cases in test-cases-tracker

2023-11-29 14:44 UTC, sagarkoshti1990 requested changes

2023-11-29 14:44 UTC, sagarkoshti1990 commented on apps/front-end/src/routes/routes.js
> +  },
you add remote but this route not working please check on priority

2023-11-29 14:44 UTC, sagarkoshti1990 commented on modules/assessment/src/pages/Assessment.js
> +    // }
Remove

2023-11-30 06:47 UTC, Aar-if commented on apps/front-end/src/routes/routes.js
> +  },
DONE

2023-11-30 06:47 UTC, Aar-if commented on modules/assessment/src/pages/Assessment.js
> +    // }
DONE

2023-11-30 12:44 UTC, merged