Task #209532  - Optimising upload images
tekdi/eg-website pull request #773
Opened 2023-12-06 12:27 UTC by Aar-if

https://tracker.tekdi.net/issues/209532?issue_count=138&issue_position=14&next_issue_id=209495&prev_issue_id=209533

![image (1)](https://github.com/tekdi/eg-website/assets/102529125/1f0744d4-c19e-4e58-a5eb-d5ff675112e6)

2023-12-06 12:30 UTC, manojLondhe commented on lib/common-lib/src/components/SunbirdPlayer.js
> +    // if (telemetry?.eid === 'ASSESS') {
use /* for. multiline comment

2023-12-06 12:33 UTC, manojLondhe commented on lib/common-lib/src/components/Camera.js
> +        maxSizeMB: 1,
Are we sure 1 MB is max? @sagar-techjoomla @Aar-if 

Can we use config for this?

2023-12-06 12:33 UTC, manojLondhe commented on lib/common-lib/src/components/Camera.js
> +        maxWidthOrHeight: Math.max(640, 480),
this is not max we need, this is minium we need for attendance photos

2023-12-06 12:34 UTC, manojLondhe commented on apps/front-end/src/component/formCustomeInputs/FileUpload.js
> +  console.log({ value });
remove console logs

2023-12-11 07:07 UTC, sagarkoshti1990 requested changes

2023-12-11 07:07 UTC, sagarkoshti1990 commented on apps/front-end/src/component/formCustomeInputs/FileUpload.js
> +        const maxWidthOrHeight = Math.max(width || 640, height || 480);
please change to `const maxWidthOrHeight = Math.max(width || 1280, height || 740);`

2023-12-11 07:07 UTC, sagarkoshti1990 commented on lib/common-lib/src/components/Camera.js
> +        maxWidthOrHeight: Math.max(640, 480),
please change to `maxWidthOrHeight: Math.max(width || 1280, height || 740);`

2023-12-11 07:09 UTC, Aar-if commented on apps/front-end/src/component/formCustomeInputs/FileUpload.js
> +        const maxWidthOrHeight = Math.max(width || 640, height || 480);
Yes

2023-12-11 07:44 UTC, sagarkoshti1990 requested changes

2023-12-11 07:44 UTC, sagarkoshti1990 commented on yarn.lock
> +attr-accept@^2.2.2:
please undo this.

2023-12-11 07:44 UTC, sagarkoshti1990 commented on modules/assessment/package.json
> +    "browser-image-compression": "^2.0.2",
please undo this.

2023-12-11 07:44 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/front-end/BenificiaryProfilePhoto.js
> +              // value={formData?.[`profile_photo_${page}`]?.id}
please add value.

2023-12-11 12:37 UTC, Aar-if commented on lib/common-lib/src/components/SunbirdPlayer.js
> +    // if (telemetry?.eid === 'ASSESS') {
Added

2023-12-11 12:41 UTC, Aar-if commented on lib/common-lib/src/components/Camera.js
> +        maxSizeMB: 1,
This is the max compression limit, we can use config in KB as well but it will result impacting the image quality.

2023-12-11 12:45 UTC, Aar-if commented on lib/common-lib/src/components/Camera.js
> +        maxWidthOrHeight: Math.max(640, 480),
Done

2023-12-11 16:53 UTC, Aar-if commented on apps/front-end/src/pages/front-end/BenificiaryProfilePhoto.js
> +              // value={formData?.[`profile_photo_${page}`]?.id}
Done

2023-12-11 16:54 UTC, Aar-if commented on modules/assessment/package.json
> +    "browser-image-compression": "^2.0.2",
I have removed the assessment module since it is not required

2023-12-12 09:42 UTC, sagarkoshti1990 approved these changes

2023-12-12 09:42 UTC, merged