Task #210084 Change the camp session list UI
tekdi/eg-website pull request #816
Opened 2023-12-15 09:02 UTC by chaitanyakole

### I have ensured that following `Pull Request Checklist` is taken care of before sending this PR
* [ ] Code is formatted as per format decided
* [ ] Updated acceptance criteria in tracker
* [ ] Updated test cases in test-cases-tracker
https://tracker.tekdi.net/issues/210084

2023-12-18 06:20 UTC, manojLondhe commented
@coderabbitai review

2023-12-18 06:35 UTC, manojLondhe commented
@coderabbitai review

2023-12-18 06:45 UTC, manojLondhe commented on apps/front-end/src/pages/front-end/Camp/CampDashboard.js
>              </VStack>
ignore this if needed

2023-12-20 09:53 UTC, sagarkoshti1990 requested changes

2023-12-20 09:53 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/admin/camps/CampSessionList.js
>                      <CheckCircleIcon color="greenIconColor" size="24px" />
use icons from `<IconByName name="CheckCircleIcon" _icon={{color:"greenIconColor",size:"24px"}} />` component

2023-12-20 09:53 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/admin/camps/CampSessionList.js
> +                    background={"#FF0000"}
use theme color.

2023-12-20 09:53 UTC, sagarkoshti1990 commented on apps/front-end/src/pages/admin/camps/CampSessionList.js
> +            {!["incomplete", "complete"].includes(
Please refactor this modal body code.

2023-12-20 11:26 UTC, sagarkoshti1990 approved these changes

2023-12-20 11:26 UTC, merged